create database if not exists your_db;

create table your_db.user
(
    id          bigint auto_increment comment '主键'
        primary key,
    username    varchar(128) default '新用户'          not null comment '用户名',
    account     varchar(128) default 'account'         not null comment '账号',
    password    varchar(128) default '12345678'        not null comment '密码',
    avatar_url  varchar(512) default ''                not null comment '用户头像',
    gender      tinyint      default 0                 not null comment '性别（0-未设置，1-男，2-女）',
    tags        varchar(512) default '[]'              null comment '标签',
    role        tinyint      default 0                 not null comment '角色（0-普通用户，1-管理员）',
    create_time timestamp    default CURRENT_TIMESTAMP not null comment '创建时间',
    update_time timestamp    default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment '更新时间',
    deleted     tinyint      default 0                 not null comment '是否删除（0-未删除，1-已删除）'
)
    comment '用户表';

INSERT INTO rekker.user (username, account, password, gender, tags) VALUES
                                                                         ('码农小明', 'dev_xm123', '12345678', 1, '["Java", "SpringBoot", "MySQL"]'),
                                                                         ('Java架构师', 'java_arch', '12345678', 1, '["Java", "SpringCloud", "MyBatis", "Redis", "Docker"]'),
                                                                         ('前端小花', 'fe_xiaohua', '12345678', 2, '["JavaScript", "Vue", "React"]'),
                                                                         ('全栈开发', 'fullstack', '12345678', 1, '["Java", "Vue", "MySQL", "Redis"]'),
                                                                         ('运维工程师', 'ops_li', '12345678', 1, '["Linux", "Docker", "Kubernetes"]'),
                                                                         ('后端开发', 'backend_dev', '12345678', 1, '["Java", "SpringBoot", "MySQL", "Redis"]'),
                                                                         ('微服务专家', 'micro_svc', '12345678', 1, '["Java", "SpringCloud", "Docker", "Kubernetes"]'),
                                                                         ('数据工程师', 'data_eng', '12345678', 1, '["Python", "MySQL", "Redis", "Kafka"]'),
                                                                         ('云原生开发', 'cloud_native', '12345678', 1, '["Java", "Docker", "Kubernetes", "AWS"]'),
                                                                         ('前端大神', 'fe_master', '12345678', 2, '["JavaScript", "Vue", "React", "TypeScript"]'),
                                                                         ('架构师老王', 'arch_wang', '12345678', 1, '["Java", "SpringCloud", "分布式", "高并发"]'),
                                                                         ('数据库专家', 'db_expert', '12345678', 1, '["MySQL", "Redis", "MongoDB", "Elasticsearch"]'),
                                                                         ('消息队列', 'mq_special', '12345678', 1, '["RabbitMQ", "Kafka", "Java", "SpringBoot"]'),
                                                                         ('运维大神', 'ops_god', '12345678', 1, '["Linux", "Docker", "Kubernetes", "Jenkins"]'),
                                                                         ('全栈工程师', 'full_stack', '12345678', 1, '["Java", "Vue", "MySQL", "Docker"]'),
                                                                         ('Java新手', 'java_newbie', '12345678', 2, '["Java", "SpringBoot", "MySQL"]'),
                                                                         ('前端萌新', 'fe_beginner', '12345678', 2, '["JavaScript", "Vue"]'),
                                                                         ('DevOps', 'devops_eng', '12345678', 1, '["Docker", "Kubernetes", "Jenkins", "Linux"]'),
                                                                         ('缓存专家', 'cache_master', '12345678', 1, '["Redis", "Java", "SpringBoot"]'),
                                                                         ('搜索工程师', 'search_eng', '12345678', 1, '["Elasticsearch", "Java", "SpringBoot"]'),
                                                                         ('中间件开发', 'middleware', '12345678', 1, '["Java", "RabbitMQ", "Kafka", "Redis"]'),
                                                                         ('Web开发', 'web_dev', '12345678', 1, '["Java", "Vue", "MySQL", "Redis"]'),
                                                                         ('移动后端', 'mobile_be', '12345678', 1, '["Java", "SpringBoot", "MySQL", "Redis"]'),
                                                                         ('电商架构', 'ecom_arch', '12345678', 1, '["Java", "SpringCloud", "分布式", "高并发"]'),
                                                                         ('金融科技', 'fintech_dev', '12345678', 1, '["Java", "SpringBoot", "MySQL", "Redis"]'),
                                                                         ('AI工程师', 'ai_engineer', '12345678', 1, '["Python", "Java", "MySQL"]'),
                                                                         ('大数据开发', 'bigdata_dev', '12345678', 1, '["Java", "Kafka", "Elasticsearch"]'),
                                                                         ('测试开发', 'test_dev', '12345678', 2, '["Java", "SpringBoot", "MySQL"]'),
                                                                         ('安全工程师', 'security_eng', '12345678', 1, '["Java", "Linux", "SpringBoot"]'),
                                                                         ('性能优化', 'perf_opt', '12345678', 1, '["Java", "MySQL", "Redis", "高并发"]'),
                                                                         ('容器专家', 'container_exp', '12345678', 1, '["Docker", "Kubernetes", "Java"]'),
                                                                         ('CI/CD专家', 'cicd_master', '12345678', 1, '["Jenkins", "Docker", "Kubernetes"]'),
                                                                         ('监控系统', 'monitor_sys', '12345678', 1, '["Java", "Elasticsearch", "Kafka"]'),
                                                                         ('日志系统', 'log_system', '12345678', 1, '["Java", "Elasticsearch", "Kafka"]'),
                                                                         ('配置中心', 'config_center', '12345678', 1, '["Java", "SpringCloud", "Redis"]'),
                                                                         ('网关开发', 'gateway_dev', '12345678', 1, '["Java", "SpringCloud", "Nginx"]'),
                                                                         ('认证授权', 'auth_dev', '12345678', 1, '["Java", "SpringBoot", "Redis"]'),
                                                                         ('订单系统', 'order_system', '12345678', 1, '["Java", "MySQL", "Redis", "分布式"]'),
                                                                         ('支付系统', 'payment_sys', '12345678', 1, '["Java", "MySQL", "Redis", "高并发"]'),
                                                                         ('用户中心', 'user_center', '12345678', 2, '["Java", "SpringBoot", "MySQL"]'),
                                                                         ('商品系统', 'product_sys', '12345678', 1, '["Java", "MySQL", "Redis"]'),
                                                                         ('库存系统', 'inventory_sys', '12345678', 1, '["Java", "MySQL", "Redis"]'),
                                                                         ('推荐系统', 'recommend_sys', '12345678', 1, '["Java", "Redis", "SpringBoot"]'),
                                                                         ('搜索系统', 'search_system', '12345678', 1, '["Java", "Elasticsearch", "SpringBoot"]'),
                                                                         ('风控系统', 'risk_control', '12345678', 1, '["Java", "SpringBoot", "MySQL"]'),
                                                                         ('数据分析师', 'data_analyst', '12345678', 2, '["Python", "MySQL", "Redis"]'),
                                                                         ('后端组长', 'backend_lead', '12345678', 1, '["Java", "SpringCloud", "MySQL", "Redis"]'),
                                                                         ('前端组长', 'fe_lead', '12345678', 2, '["JavaScript", "Vue", "React", "TypeScript"]'),
                                                                         ('技术经理', 'tech_manager', '12345678', 1, '["Java", "SpringCloud", "分布式", "管理"]'),
                                                                         ('CTO助理', 'cto_assist', '12345678', 2, '["Java", "SpringCloud", "管理", "架构"]');